#!/bin/sh

# Adapted from /usr/lib/rpm/brp-strip-comment-note

set -e

if [ $# = 0 ]; then
	exit 0
fi

if [ "$BUVER" = "" ]; then
	BUVER=2.22
fi

STRIP=/build/toolchain/lin64/binutils-$BUVER/bin/$TARGET-strip
OBJDUMP=/build/toolchain/lin64/binutils-$BUVER/bin/$TARGET-objdump

# Strip .comment and .note sections (the latter only if it is not allocated)
# for already stripped elf files in the build root
for f in `find $@ -type f \( -perm -0100 -or -perm -0010 -or -perm -0001 \) -exec file {} \; | \
	sed -n -e 's/^\(.*\):[ 	]*ELF.*, not stripped/\1/p'`; do
	note="-R .note"
	if $OBJDUMP -h $f | grep '^[ 	]*[0-9]*[ 	]*.note[ 	]' -A 1 | \
		grep ALLOC >/dev/null; then
		note=
	fi
	echo "$TARGET-strip -R .comment $note $f"
	$STRIP -R .comment $note "$f"
done
