#!/bin/sh

# These are the build root policies that VMware invokes at the end
# of the install.sh scriptlet.

set -e

COMMON=$(dirname $0)

# Strip ELF binaries (Red Hat uses GNU binutils).
$COMMON/brp-strip "$@"

# Strip even more sections (Red Hat uses GNU binutils).
$COMMON/brp-strip-comment-note "$@"

# Strip shared libraries (Red Hat uses GNU binutils).
#$COMMON/brp-strip-shared "$@"
